vich_uploader:
    db_driver: orm

    mappings:
        featured_images:
            uri_prefix: '%app.path.featured_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.featured_images%'
        article_attachements:
            uri_prefix: '%app.path.article_attachments%'
            upload_destination: '%kernel.project_dir%/public%app.path.article_attachments%'
            delete_on_remove:   true
            inject_on_load:     true
            delete_on_update:   true

